version: 1.0.{build}
init:
- ps: >-
    choco install docker-desktop
    
    Install-WindowsFeature -Name Hyper-V -IncludeManagementTools -Restart
build_script:
- ps: >-
    docker run -it heroku/functions-buildpacks ls /
